In [1]:
import pandas as pd

In [2]:
def function(file_path):
    
    df = pd.read_csv(file_path, low_memory=False, encoding='cp949')
    
    # string -> float
    df['총인구(명)'] = df['총인구(명)'].replace('X', 0).astype(str)
    df['총인구(명)'] = df['총인구(명)'].astype(float)
    
    # 나이 정의
    ages = []
    for i in range(6,22):
        ages.append(' '+str(i)+'세')
        
    # 6세 ~ 21세 빼고 삭제
    df = df[df['연령별'].isin(ages)]
    
    # 쓸데 없는 column 삭제
    df = df.drop(['C연령별','내국인_성비', '내국인_여자(명)','내국인_남자(명)','내국인(명)','총인구_성비','총인구_여자(명)','총인구_남자(명)'], axis=1)
    
    #행정구역별(읍면동)에 따라 6세~21세 총인구 종합
    new_df = df.groupby(['C행정구역별(읍면동)','행정구역별(읍면동)','시점'])['총인구(명)'].sum().reset_index()
    
    
    return new_df

In [3]:
file_path = []
df = []
for i in range(2015,2022):
    file_path.append('./Data/'+str(i)+'.csv')
    
for path in file_path:
    df.append(function(path))

In [6]:
# 병합

concat_df = pd.concat(df)

concat_df = concat_df.sort_values(by=['C행정구역별(읍면동)','시점'])

concat_df.head(30)

   C행정구역별(읍면동) 행정구역별(읍면동)    시점     총인구(명)
0            0         전국  2015  8837760.0
0            0         전국  2016  8603585.0
0            0         전국  2017  8388551.0
0            0         전국  2018  8207704.0
0            0         전국  2019  8000335.0
0            0         전국  2020  7822121.0
0            0         전국  2021  7640590.0
1            3         동부  2015  7419152.0
1            3         동부  2016  7204238.0
1            3         동부  2017  7005190.0
1            3         동부  2018  6841066.0
1            3         동부  2019  6668233.0
1            3         동부  2020  6522078.0
1            3         동부  2021  6375121.0
2            4         읍부  2015   837137.0
2            4         읍부  2016   831990.0
2            4         읍부  2017   827207.0
2            4         읍부  2018   844073.0
2            4         읍부  2019   834715.0
2            4         읍부  2020   823709.0
2            4         읍부  2021   820805.0
3            5         면부  2015   581471.0
3            5         면부  2016   567357.0
3            5         면부  2017   556154.0
3            5         면부  2018   522565.0
3            5         면부  2019   497387.0
3            5         면부  2020   476334.0
3            5         면부  2021   444664.0
4           11      서울특별시  2015  1522168.0
4           11      서울특별시  2016  1464123.0

In [7]:
# csv로 저장

concat_df.to_csv('2015-2021 전국 읍면동 학령인구 데이터.csv', index=False)