In [1]:
import pandas as pd

df1 = pd.read_csv('../makeDataset/dataset/processedData/31_1.csv')
df2 = pd.read_csv('../makeDataset/dataset/no_NaN_dataset_final.csv')

In [2]:
df1.head()

,행정구역(시도),행정구역(시군구),연도,총인구수(명),유치원 수,초등학교 수,출생건수,사망건수,혼인건수,이혼건수,학령인구(명),총인구수-학령인구(명),행정구역
0,서울특별시,종로구,2010,170578,17,14,1107,852,1011,396,29164,141414,서울특별시 종로구
1,서울특별시,중구,2010,132822,13,12,1170,671,1049,378,19628,113194,서울특별시 중구
2,서울특별시,용산구,2010,244853,19,15,2312,1086,1784,528,37318,207535,서울특별시 용산구
3,서울특별시,성동구,2010,309093,31,20,2886,1226,2306,672,51562,257531,서울특별시 성동구
4,서울특별시,광진구,2010,375463,42,22,3366,1290,2672,811,67422,308041,서울특별시 광진구

In [3]:
df2.head()

,행정구역(시도),행정구역(시군구),연도,총인구수(명),유치원 수,초등학교 수,출생건수,사망건수,혼인건수,이혼건수,학령인구(명),총인구수-학령인구(명),행정구역
0,서울특별시,종로구,2010,170578,17,14,1107,852,1011,396,29164,141414,서울특별시 종로구
1,서울특별시,중구,2010,132822,13,12,1170,671,1049,378,19628,113194,서울특별시 중구
2,서울특별시,용산구,2010,244853,19,15,2312,1086,1784,528,37318,207535,서울특별시 용산구
3,서울특별시,성동구,2010,309093,31,20,2886,1226,2306,672,51562,257531,서울특별시 성동구
4,서울특별시,광진구,2010,375463,42,22,3366,1290,2672,811,67422,308041,서울특별시 광진구

In [4]:
df1.equals(df2)

False

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2899 entries, 0 to 2898
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   행정구역(시도)      2899 non-null   object
 1   행정구역(시군구)     2899 non-null   object
 2   연도            2899 non-null   int64
 3   총인구수(명)       2899 non-null   int64
 4   유치원 수         2899 non-null   int64
 5   초등학교 수        2899 non-null   int64
 6   출생건수          2899 non-null   int64
 7   사망건수          2899 non-null   int64
 8   혼인건수          2899 non-null   int64
 9   이혼건수          2899 non-null   int64
 10  학령인구(명)       2899 non-null   int64
 11  총인구수-학령인구(명)  2899 non-null   int64
 12  행정구역          2899 non-null   object
dtypes: int64(10), object(3)
memory usage: 294.6+ KB

In [6]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2899 entries, 0 to 2898
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   행정구역(시도)      2899 non-null   object
 1   행정구역(시군구)     2899 non-null   object
 2   연도            2899 non-null   int64
 3   총인구수(명)       2899 non-null   int64
 4   유치원 수         2899 non-null   int64
 5   초등학교 수        2899 non-null   int64
 6   출생건수          2899 non-null   int64
 7   사망건수          2899 non-null   int64
 8   혼인건수          2899 non-null   int64
 9   이혼건수          2899 non-null   int64
 10  학령인구(명)       2899 non-null   int64
 11  총인구수-학령인구(명)  2899 non-null   int64
 12  행정구역          2899 non-null   object
dtypes: int64(10), object(3)
memory usage: 294.6+ KB

In [8]:
(df1 == df2).count()

행정구역(시도)        2899
행정구역(시군구)       2899
연도              2899
총인구수(명)         2899
유치원 수           2899
초등학교 수          2899
출생건수            2899
사망건수            2899
혼인건수            2899
이혼건수            2899
학령인구(명)         2899
총인구수-학령인구(명)    2899
행정구역            2899
dtype: int64

In [9]:
import pandas as pd

# 두 데이터 프레임 df1, df2
different_rows = pd.concat([df1, df2]).drop_duplicates(keep=False)

In [10]:
merged_df = pd.merge(df1, df2, how='outer', indicator=True)
different_rows = merged_df[merged_df['_merge'] != 'both']

In [12]:
mask = df1.ne(df2).any(axis=1)
different_rows = df1[mask]
different_rows

,행정구역(시도),행정구역(시군구),연도,총인구수(명),유치원 수,초등학교 수,출생건수,사망건수,혼인건수,이혼건수,학령인구(명),총인구수-학령인구(명),행정구역
26,부산광역시,서구,2010,62594,16,17,609,459,449,142,20179,53174,부산광역시 서구
42,대구광역시,서구,2010,607083,74,51,5404,2400,3366,1116,40098,467710,대구광역시 서구
48,인천광역시,동구,2010,473423,68,33,4653,1877,3088,1288,13286,374058,인천광역시 동구
96,경기도,양주시,2010,564141,90,53,5821,2404,3220,1365,39775,445671,경기도 양주시
249,부산광역시,서구,2011,64733,12,16,567,467,399,163,19182,55253,부산광역시 서구
265,대구광역시,서구,2011,606542,77,52,5333,2472,3265,1039,37875,471303,대구광역시 서구
271,인천광역시,동구,2011,495469,71,36,5010,1994,3200,1135,12874,394606,인천광역시 동구
319,경기도,양주시,2011,578485,92,54,6125,2409,3292,1485,40384,458865,경기도 양주시
472,부산광역시,서구,2012,65806,12,16,671,418,418,165,18230,56458,부산광역시 서구
488,대구광역시,서구,2012,606557,80,52,5463,2462,3322,1042,35957,475425,대구광역시 서구
494,인천광역시,동구,2012,503597,71,36,5333,2164,3224,1384,12259,404324,인천광역시 동구
542,경기도,양주시,2012,599539,95,55,6081,2525,3201,1520,40045,476956,경기도 양주시
695,부산광역시,서구,2013,69873,13,17,680,473,479,157,17280,59979,부산광역시 서구
711,대구광역시,서구,2013,610358,85,53,5097,2494,3391,1090,33552,482778,대구광역시 서구
717,인천광역시,동구,2013,507021,76,37,4699,2155,3115,1294,11734,409654,인천광역시 동구
765,경기도,양주시,2013,618305,96,55,5505,2624,3397,1601,39478,492911,경기도 양주시
918,부산광역시,서구,2014,79619,13,17,925,449,624,155,16500,68430,부산광역시 서구
934,대구광역시,서구,2014,606433,89,53,5025,2458,3038,1149,31055,484425,대구광역시 서구
940,인천광역시,동구,2014,514656,78,37,4732,2214,3067,1326,11301,419370,인천광역시 동구
988,경기도,양주시,2014,636256,100,56,5455,2550,3179,1579,39419,509640,경기도 양주시
1141,부산광역시,서구,2015,94608,14,17,1365,466,768,185,15414,81375,부산광역시 서구
1157,대구광역시,서구,2015,602641,90,54,5049,2651,3117,990,28685,486012,대구광역시 서구
1163,인천광역시,동구,2015,531395,82,37,4883,2223,3256,1293,10815,436875,인천광역시 동구
1211,경기도,양주시,2015,653454,108,59,5588,2720,3269,1520,39161,526512,경기도 양주시
1364,부산광역시,서구,2016,108909,16,18,1601,493,839,204,14405,93534,부산광역시 서구
1380,대구광역시,서구,2016,591891,85,54,4504,2684,2786,952,26228,481225,대구광역시 서구
1386,인천광역시,동구,2016,530982,87,38,4521,2342,3036,1290,10368,439033,인천광역시 동구
1434,경기도,양주시,2016,662154,109,60,5218,2819,3037,1470,38501,536127,경기도 양주시
1587,부산광역시,서구,2017,117382,19,18,1731,511,905,244,13476,100609,부산광역시 서구
1603,대구광역시,서구,2017,578068,83,55,3706,2692,2521,930,23891,473481,대구광역시 서구
1609,인천광역시,동구,2017,536578,87,38,3850,2455,2826,1361,9940,446241,인천광역시 동구
1657,경기도,양주시,2017,665321,110,60,4422,2983,2675,1439,38520,540824,경기도 양주시
1810,부산광역시,서구,2018,122957,20,17,1607,556,851,270,13219,104743,부산광역시 서구
1826,대구광역시,서구,2018,573413,81,55,3041,2809,2379,1018,21749,473328,대구광역시 서구
1832,인천광역시,동구,2018,537161,85,38,3782,2694,2679,1272,9296,448879,인천광역시 동구
1880,경기도,양주시,2018,681828,110,61,4120,3234,2759,1509,38537,555730,경기도 양주시
2033,부산광역시,서구,2019,129566,21,17,1449,556,804,287,12601,109592,부산광역시 서구
2049,대구광역시,서구,2019,568887,78,55,2927,2749,2249,1064,19595,473580,대구광역시 서구
2055,인천광역시,동구,2019,532704,77,38,3333,2617,2311,1359,8751,447264,인천광역시 동구
2103,경기도,양주시,2019,701830,110,64,3855,3288,2630,1564,38524,575046,경기도 양주시
2256,부산광역시,서구,2020,137957,22,18,1312,602,712,299,12351,115849,부산광역시 서구
2272,대구광역시,서구,2020,558631,79,56,2373,2939,1895,987,18108,468056,대구광역시 서구
2278,인천광역시,동구,2020,525354,74,39,2831,2728,2095,1308,8169,443042,인천광역시 동구
2326,경기도,양주시,2020,713321,108,65,3683,3384,2362,1593,39092,586913,경기도 양주시
2479,부산광역시,서구,2021,142918,21,18,1294,609,699,348,11932,119074,부산광역시 서구
2495,대구광역시,서구,2021,544926,77,56,2231,2890,1532,922,16751,458670,대구광역시 서구
2501,인천광역시,동구,2021,518272,70,39,2446,2832,1788,1231,7889,438722,인천광역시 동구
2549,경기도,양주시,2021,733798,111,67,3596,3716,2458,1565,39368,606369,경기도 양주시
2702,부산광역시,서구,2022,143207,22,18,1283,733,651,303,11730,118334,부산광역시 서구
2718,대구광역시,서구,2022,536989,73,56,2012,3539,1599,832,15622,454491,대구광역시 서구
2724,인천광역시,동구,2022,506181,65,39,2157,3331,1785,1076,7318,430549,인천광역시 동구
2772,경기도,양주시,2022,737353,111,68,3609,4463,2586,1449,39685,612006,경기도 양주시