In [30]:
import pandas as pd

In [31]:
filePath = './dataset/adjacency_matrix.csv'
distance_matrix = pd.read_csv(filePath, index_col=0)

distance_matrix.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청음성군,충청제천시,충청증평군,충청진천군,충청천안시,충청청양군,충청청주시,충청충주시,충청태안군,충청홍성군
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,0.000000,78.530302,32.832761,42.145885,56.412485,87.339480,42.478539,73.013896,95.861557,71.297142,...,138.334056,91.674595,157.151627,161.804535,185.372602,233.452786,177.343533,119.216734,254.188657,234.314919
강원고성군,78.530302,0.000000,110.785057,120.233443,22.138478,51.457336,36.408490,133.112542,125.138624,43.255624,...,174.191634,140.912805,193.888417,192.458313,210.006736,259.421519,216.662892,161.729110,263.910596,254.120378
강원동해시,32.832761,110.785057,0.000000,9.454969,88.658337,118.287305,75.141194,69.035839,107.420730,102.723800,...,141.840711,92.569542,158.847038,166.314778,191.474382,237.099618,176.520998,120.774804,264.289199,240.721546
강원삼척시,42.145885,120.233443,9.454969,0.000000,98.104205,126.718841,84.535489,68.895896,110.677986,111.351218,...,142.403432,93.137346,158.736792,166.957057,192.415783,237.133637,175.556918,121.025102,266.104274,241.538867
강원속초시,56.412485,22.138478,88.658337,98.104205,0.000000,53.723255,14.807813,114.373119,112.894017,39.898501,...,161.730278,124.583847,181.542495,181.635948,201.022903,250.637464,203.966333,147.404910,259.605572,246.947901

In [32]:
distance_threshold = 30
local_params = 0.75
adj_params = 1 - local_params

In [33]:
dm_with_threshhold = distance_matrix[distance_matrix < distance_threshold]

In [34]:
dm_with_threshhold.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청음성군,충청제천시,충청증평군,충청진천군,충청천안시,충청청양군,충청청주시,충청충주시,충청태안군,충청홍성군
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원고성군,NaN,0.000000,NaN,NaN,22.138478,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원동해시,NaN,NaN,0.000000,9.454969,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원삼척시,NaN,NaN,9.454969,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원속초시,NaN,22.138478,NaN,NaN,0.000000,NaN,14.807813,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
# dm_with_threshhold의 모든 가중치를 역수로 취하기.
# 가중치가 0일경우 1로 바꾸기.

dm_with_threshhold = dm_with_threshhold.replace(0, 1)
dm_with_threshhold = 1 / dm_with_threshhold

dm_with_threshhold.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청음성군,충청제천시,충청증평군,충청진천군,충청천안시,충청청양군,충청청주시,충청충주시,충청태안군,충청홍성군
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원고성군,NaN,1.00000,NaN,NaN,0.04517,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원동해시,NaN,NaN,1.000000,0.105764,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원삼척시,NaN,NaN,0.105764,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원속초시,NaN,0.04517,NaN,NaN,1.00000,NaN,0.067532,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
import numpy as np

# 각 행의 합을 계산
row_sums = dm_with_threshhold.sum(axis=1) - 1

row_sums.head()

docity
강원강릉시    0.000000
강원고성군    0.045170
강원동해시    0.105764
강원삼척시    0.105764
강원속초시    0.112702
dtype: float64

In [37]:
# 각 인접 도시와의 가중치를 총합으로 나눔
normalized_df = dm_with_threshhold.div(row_sums, axis=0) * adj_params

normalized_df.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청음성군,충청제천시,충청증평군,충청진천군,충청천안시,충청청양군,충청청주시,충청충주시,충청태안군,충청홍성군
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,inf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원고성군,NaN,5.534620,NaN,NaN,0.250000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원동해시,NaN,NaN,2.363742,0.250000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원삼척시,NaN,NaN,0.250000,2.363742,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원속초시,NaN,0.100198,NaN,NaN,2.218236,NaN,0.149802,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
# 대각선 행 중 inf가 아닌 행은 0.7으로 만들기

for i in range(len(normalized_df)):
    if normalized_df.iloc[i, i] != np.inf:
        normalized_df.iloc[i, i] = local_params
    else:
        normalized_df.iloc[i, i] = 1

normalized_df.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청음성군,충청제천시,충청증평군,충청진천군,충청천안시,충청청양군,충청청주시,충청충주시,충청태안군,충청홍성군
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원고성군,NaN,0.750000,NaN,NaN,0.25,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원동해시,NaN,NaN,0.75,0.25,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원삼척시,NaN,NaN,0.25,0.75,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원속초시,NaN,0.100198,NaN,NaN,0.75,NaN,0.149802,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
result = normalized_df.sum(axis=1)

result[result - 1 > 0.00001]

Series([], dtype: float64)

In [40]:
normalized_df.to_csv('./dataset/distance_normalize_v2.csv')

In [41]:
df = pd.read_csv('./dataset/no_NaN_dataset_final.csv')

df.head()

,행정구역(시도),행정구역(시군구),연도,총인구수(명),유치원 수,초등학교 수,출생건수,사망건수,혼인건수,이혼건수,학령인구(명),총인구수-학령인구(명),행정구역
0,서울특별시,종로구,2010,170578,17,14,1107,852,1011,396,29164,141414,서울특별시 종로구
1,서울특별시,중구,2010,132822,13,12,1170,671,1049,378,19628,113194,서울특별시 중구
2,서울특별시,용산구,2010,244853,19,15,2312,1086,1784,528,37318,207535,서울특별시 용산구
3,서울특별시,성동구,2010,309093,31,20,2886,1226,2306,672,51562,257531,서울특별시 성동구
4,서울특별시,광진구,2010,375463,42,22,3366,1290,2672,811,67422,308041,서울특별시 광진구

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2899 entries, 0 to 2898
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   행정구역(시도)      2899 non-null   object
 1   행정구역(시군구)     2899 non-null   object
 2   연도            2899 non-null   int64
 3   총인구수(명)       2899 non-null   int64
 4   유치원 수         2899 non-null   int64
 5   초등학교 수        2899 non-null   int64
 6   출생건수          2899 non-null   int64
 7   사망건수          2899 non-null   int64
 8   혼인건수          2899 non-null   int64
 9   이혼건수          2899 non-null   int64
 10  학령인구(명)       2899 non-null   int64
 11  총인구수-학령인구(명)  2899 non-null   int64
 12  행정구역          2899 non-null   object
dtypes: int64(10), object(3)
memory usage: 294.6+ KB

In [43]:
def find_cityname_in_df(df, cityname, year):
    # cityname에서 첫 두글자는 시도에, 나머지는 시군구에 저장함
    
    sido = cityname[:2]
    sigungu = cityname[2:]
    
    # sido와 sigungu를 모두 포함하는 행 찾기 꼭 일치하지 않아도 되고 일부만 포함해도 됨
    
    sido_df = df[df['행정구역(시도)'].str.contains(sido)]
    # sigungu_df = sido_df[sido_df['행정구역(시군구)'].str.contains(sigungu)]
    sigungu_df = sido_df[sido_df['행정구역(시군구)'] == sigungu]
    
    
    result = sigungu_df[sigungu_df['연도'] == year]
    
    if len(result) == 0:
        sido = cityname[:2]
        sigungu = cityname[2:]
        
        sido_df = df[df['행정구역(시도)'].str.contains(sido)]
        
        sigungu_df = sido_df[sido_df['행정구역(시군구)'].str.contains(sigungu)]
        
        result = sigungu_df[sigungu_df['연도'] == year]
        
    if len(result) != 1:
        print("길이는 : " + str(len(result)))
        print(result.head())

    return result

In [44]:
def find_normalizedf_row(do, city):
    row_names = normalized_df.index
    for row_name in row_names:
        if do in row_name and city in row_name:
            return normalized_df.loc[row_name]

In [45]:
from tqdm import tqdm

processed_df = df.copy()
numeric_columns = df.select_dtypes(include=[np.number]).columns
numeric_columns = numeric_columns.drop('학령인구(명)')
error_city_list = []


for i in tqdm(range(len(df))):
    try:
        parts = df.iloc[i]['행정구역(시도)'].split()
        do = parts[0][:2]
        city = df.iloc[i]['행정구역(시군구)']
        year = df.iloc[i]['연도']

        adj_matrix = find_normalizedf_row(do, city)
        row_list = []
        

        weight = 0

        
        #tmp_df = pd.DataFrame(columns=df.columns)
            
        for j in range(len(adj_matrix)):
            try:

                adj_city_name = adj_matrix.index[j]
                adj_city_weight = adj_matrix.iloc[j]
                if pd.isna(adj_city_weight):
                    continue
                
                

                row = find_cityname_in_df(df, adj_city_name, year)
        
                    
                
                #tmp_df.insert(row)
                row[numeric_columns] *= adj_city_weight

                
                if(row.empty):
                    error_city_list.append(adj_city_name)
                    continue
                
                row_list.append(row)
            except KeyError:
                print("error 2: " + adj_matrix.index[j])
                continue
        
                
        # Sum all the rows in row_list
        new_row = pd.concat(row_list)
        
        if i == 0:
            print(new_row.head())
        
        new_row = new_row[numeric_columns]
        new_row_sum = new_row.sum()
        
        if i == 0:
            print(new_row_sum.head())

        #if i == 1:
            #print(yearlist)
            #print(new_row['연도'])
        

        # Use .loc to avoid SettingWithCopyWarning
        processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum

    except Exception as e:
        print(f"error 3:  - {str(e)}")
        print(do + " " + city)
        continue

  0%|          | 0/2899 [00:00<?, ?it/s]

/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_7600/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '2009.9999999999998' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_7600/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '223727.42453704673' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_7600/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '22.39879971901759' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_7600/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '16.59450408366822' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_7600/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1712.279415339322' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_7600/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1020.9539683077084' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_7600/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1407.682182926949' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_7600/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '507.11948703143804' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_7600/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '184172.28720925326' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
  0%|          | 2/2899 [00:00<03:09, 15.26it/s]

   행정구역(시도) 행정구역(시군구)        연도      총인구수(명)     유치원 수    초등학교 수       출생건수  \
80      경기도       고양시  5.481883  2591.253355  0.403641  0.210002  22.582085
81      경기도       과천시  6.968694   250.592151  0.024269  0.013868   2.000466
76      경기도       광명시  7.645460  1308.408258  0.178774  0.087485  14.899138
95      경기도       광주시  3.735891   464.270861  0.065053  0.044608   4.719118
82      경기도       구리시  8.306748   811.656089  0.136379  0.061991   8.091847

         사망건수       혼인건수      이혼건수  학령인구(명)  총인구수-학령인구(명)     행정구역
80  10.055573  14.637446  5.490065   219030   1993.891749  경기도 고양시
81   0.821682   1.272393  0.284295    16882    192.062056  경기도 과천시
76   4.967647  10.832970  2.540879    68038   1049.611341  경기도 광명시
95   2.117005   3.029603  1.258308    48825    373.522170  경기도 광주시
82   3.194585   5.232012  2.058090    42489    636.061350  경기도 구리시
연도           2010.000000
총인구수(명)    223727.424537
유치원 수          22.398800
초등학교 수         16.594504
출생건수         1712.279415
dtype: float64

100%|██████████| 2899/2899 [00:53<00:00, 54.60it/s]

In [46]:
print(set(error_city_list))

set()

In [47]:
# procedded_df의 '연도' 컬럼을 반올림해서 int 정수로 바꾸기

processed_df['연도'] = processed_df['연도'].round().astype(int)

In [48]:
processed_df.to_csv('./dataset/weighted_dataset_v6.csv')