In [88]:
import pandas as pd

In [89]:
filePath = 'adjacency_matrix.csv'
distance_matrix = pd.read_csv(filePath, index_col=0)

distance_matrix.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청증평군,충청진천군,충청천안시,충청청양군,충청청원군,충청청주시,충청충주시,충청태안군,충청홍성군,충청대전시
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,0.000000,78.530302,32.832761,42.145885,56.412485,87.339480,42.478539,73.013896,95.861557,71.297142,...,157.151627,161.804535,185.372602,233.452786,185.041394,177.343533,119.216734,254.188657,234.314919,204.328739
강원고성군,78.530302,0.000000,110.785057,120.233443,22.138478,51.457336,36.408490,133.112542,125.138624,43.255624,...,193.888417,192.458313,210.006736,259.421519,223.010959,216.662892,161.729110,263.910596,254.120378,244.980225
강원동해시,32.832761,110.785057,0.000000,9.454969,88.658337,118.287305,75.141194,69.035839,107.420730,102.723800,...,158.847038,166.314778,191.474382,237.099618,184.572922,176.520998,120.774804,264.289199,240.721546,201.620599
강원삼척시,42.145885,120.233443,9.454969,0.000000,98.104205,126.718841,84.535489,68.895896,110.677986,111.351218,...,158.736792,166.957057,192.415783,237.133637,183.661808,175.556918,121.025102,266.104274,241.538867,199.972114
강원속초시,56.412485,22.138478,88.658337,98.104205,0.000000,53.723255,14.807813,114.373119,112.894017,39.898501,...,181.542495,181.635948,201.022903,250.637464,210.727680,203.966333,147.404910,259.605572,246.947901,232.227327

In [90]:
distance_threshold = 60
local_params = 0.7
adj_params = 1 - local_params

In [91]:
dm_with_threshhold = distance_matrix[distance_matrix < distance_threshold]

In [92]:
dm_with_threshhold.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청증평군,충청진천군,충청천안시,충청청양군,충청청원군,충청청주시,충청충주시,충청태안군,충청홍성군,충청대전시
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,0.000000,NaN,32.832761,42.145885,56.412485,NaN,42.478539,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원고성군,NaN,0.000000,NaN,NaN,22.138478,51.457336,36.408490,NaN,NaN,43.255624,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원동해시,32.832761,NaN,0.000000,9.454969,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원삼척시,42.145885,NaN,9.454969,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원속초시,56.412485,22.138478,NaN,NaN,0.000000,53.723255,14.807813,NaN,NaN,39.898501,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
# dm_with_threshhold의 모든 가중치를 역수로 취하기.
# 가중치가 0일경우 1로 바꾸기.

dm_with_threshhold = dm_with_threshhold.replace(0, 1)
dm_with_threshhold = 1 / dm_with_threshhold

dm_with_threshhold.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청증평군,충청진천군,충청천안시,충청청양군,충청청원군,충청청주시,충청충주시,충청태안군,충청홍성군,충청대전시
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,1.000000,NaN,0.030457,0.023727,0.017727,NaN,0.023541,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원고성군,NaN,1.00000,NaN,NaN,0.045170,0.019434,0.027466,NaN,NaN,0.023118,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원동해시,0.030457,NaN,1.000000,0.105764,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원삼척시,0.023727,NaN,0.105764,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원속초시,0.017727,0.04517,NaN,NaN,1.000000,0.018614,0.067532,NaN,NaN,0.025064,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
import numpy as np

# 각 행의 합을 계산
row_sums = dm_with_threshhold.sum(axis=1) - 1

row_sums.head()

docity
강원강릉시    0.117457
강원고성군    0.115188
강원동해시    0.183397
강원삼척시    0.197967
강원속초시    0.174106
dtype: float64

In [95]:
# 각 인접 도시와의 가중치를 총합으로 나눔
normalized_df = dm_with_threshhold.div(row_sums, axis=0) * adj_params

normalized_df.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청증평군,충청진천군,충청천안시,충청청양군,충청청원군,충청청주시,충청충주시,충청태안군,충청홍성군,충청대전시
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,2.554137,NaN,0.077792,0.060602,0.045276,NaN,0.060128,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원고성군,NaN,2.604431,NaN,NaN,0.117643,0.050613,0.071534,NaN,NaN,0.060210,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원동해시,0.049822,NaN,1.635796,0.173009,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원삼척시,0.035956,NaN,0.160276,1.515404,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원속초시,0.030544,0.077832,NaN,NaN,1.723086,0.032073,0.116363,NaN,NaN,0.043187,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
# 대각선 행은 0으로 만들기

np.fill_diagonal(normalized_df.values, local_params)

In [97]:
normalized_df.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청증평군,충청진천군,충청천안시,충청청양군,충청청원군,충청청주시,충청충주시,충청태안군,충청홍성군,충청대전시
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,0.700000,NaN,0.077792,0.060602,0.045276,NaN,0.060128,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원고성군,NaN,0.700000,NaN,NaN,0.117643,0.050613,0.071534,NaN,NaN,0.060210,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원동해시,0.049822,NaN,0.700000,0.173009,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원삼척시,0.035956,NaN,0.160276,0.700000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원속초시,0.030544,0.077832,NaN,NaN,0.700000,0.032073,0.116363,NaN,NaN,0.043187,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
result = normalized_df.sum()

In [99]:
normalized_df.to_csv('./distance_normalize_v2.csv')

In [100]:
df = pd.read_csv('./no_NaN_dataset.csv')

df.head()

,행정구역(시도),행정구역(시군구),연도,총인구수(명),총인구수증감,총인구수증감률,유치원 수,초등학교 수,출생건수,사망건수,혼인건수,이혼건수,순이동,학령인구(명),학령인구증감률,지가 변동률
0,서울특별시,종로구,2013,160070.0,-5137.0,-3.109432,17.0,14.0,873.0,840.0,877.0,348.0,-5331.0,25113.0,-5.763819,1.201
1,서울특별시,중구,2013,130465.0,-2895.0,-44.009562,13.0,12.0,1022.0,685.0,860.0,320.0,-3317.0,17356.0,-5.318859,0.604
2,서울특별시,용산구,2013,239740.0,-3492.0,-1.435666,17.0,15.0,2129.0,1058.0,1795.0,450.0,-4688.0,34734.0,-3.180488,-2.113
3,서울특별시,성동구,2013,299337.0,-267.0,-0.089118,29.0,20.0,2838.0,1294.0,2432.0,613.0,-1957.0,46055.0,-3.052310,0.277
4,서울특별시,광진구,2013,368927.0,-2386.0,-0.642585,38.0,22.0,2990.0,1331.0,2685.0,743.0,-4362.0,60341.0,-4.156739,0.454

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1823 entries, 0 to 1822
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   행정구역(시도)   1823 non-null   object
 1   행정구역(시군구)  1823 non-null   object
 2   연도         1823 non-null   int64
 3   총인구수(명)    1823 non-null   float64
 4   총인구수증감     1823 non-null   float64
 5   총인구수증감률    1823 non-null   float64
 6   유치원 수      1823 non-null   float64
 7   초등학교 수     1823 non-null   float64
 8   출생건수       1823 non-null   float64
 9   사망건수       1823 non-null   float64
 10  혼인건수       1823 non-null   float64
 11  이혼건수       1823 non-null   float64
 12  순이동        1823 non-null   float64
 13  학령인구(명)    1823 non-null   float64
 14  학령인구증감률    1823 non-null   float64
 15  지가 변동률     1823 non-null   float64
dtypes: float64(13), int64(1), object(2)
memory usage: 228.0+ KB

In [102]:
def find_cityname_in_df(df, cityname, year):
    # cityname에서 첫 두글자는 시도에, 나머지는 시군구에 저장함
    
    sido = cityname[:2]
    sigungu = cityname[2:]
    
    # sido와 sigungu를 모두 포함하는 행 찾기 꼭 일치하지 않아도 되고 일부만 포함해도 됨
    
    sido_df = df[df['행정구역(시도)'].str.contains(sido)]
    sigungu_df = sido_df[sido_df['행정구역(시군구)'].str.contains(sigungu)]
    
    result = sigungu_df[sigungu_df['연도'] == year]
    
    if len(result) == 0:
        sido = cityname[:2]
        sigungu = cityname[3:]
        
        sido_df = df[df['행정구역(시도)'].str.contains(sido)]
        sigungu_df = sido_df[sido_df['행정구역(시군구)'].str.contains(sigungu)]
        
        result = sigungu_df[sigungu_df['연도'] == year]

    return result

In [103]:
def find_normalizedf_row(do, city):
    row_names = normalized_df.index
    for row_name in row_names:
        if do in row_name and city in row_name:
            return normalized_df.loc[row_name]

In [104]:
processed_df = df.copy()
numeric_columns = df.select_dtypes(include=[np.number]).columns
error_city_list = []

for i in range(len(df)):
    try:
        parts = df.iloc[i]['행정구역(시도)'].split()
        do = parts[0][:2]
        city = df.iloc[i]['행정구역(시군구)']
        year = df.iloc[i]['연도']

        adj_matrix = find_normalizedf_row(do, city)
        row_list = []

        for j in range(len(adj_matrix)):
            try:
                adj_city_name = adj_matrix.index[j]
                adj_city_weight = adj_matrix.iloc[j]
                if pd.isna(adj_city_weight):
                    continue

                row = find_cityname_in_df(df, adj_city_name, year)
                row[numeric_columns] *= adj_city_weight
                
                if(row.empty):
                    error_city_list.append(adj_city_name)
                    continue
                
                row_list.append(row)
            except KeyError:
                print("error 2: " + adj_matrix.index[j])
                continue
        
        # Sum all the rows in row_list
        new_row = pd.concat(row_list)
        new_row = new_row[numeric_columns]
        new_row_sum = new_row.sum()

        # Use .loc to avoid SettingWithCopyWarning
        processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum

    except Exception as e:
        print(f"error 3:  - {str(e)}")
        continue

/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_26766/2713534831.py:40: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '2015.9681193139468' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum

error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()
error 3:  - object of type 'NoneType' has no len()

In [105]:
len(error_city_list)

3514

In [106]:
print(set(error_city_list))

{'충청고운동', '충청청원군', '경기옹진군', '대구시동구', '인천시남구', '충청소정면', '대구시남구', '인천시미추홀구', '충청소담동', '충청연기군', '경상기장군', '대구시수성구.1', '대구시달서구.1', '경상대구시', '경기강화군', '충청조치원읍', '충청당진군', '충청대전시', '충청부강면'}