In [1]:
import pandas as pd

In [2]:
filePath = './dataset/adjacency_matrix.csv'
distance_matrix = pd.read_csv(filePath, index_col=0)

distance_matrix.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청음성군,충청제천시,충청증평군,충청진천군,충청천안시,충청청양군,충청청주시,충청충주시,충청태안군,충청홍성군
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,0.000000,78.530302,32.832761,42.145885,56.412485,87.339480,42.478539,73.013896,95.861557,71.297142,...,138.334056,91.674595,157.151627,161.804535,185.372602,233.452786,177.343533,119.216734,254.188657,234.314919
강원고성군,78.530302,0.000000,110.785057,120.233443,22.138478,51.457336,36.408490,133.112542,125.138624,43.255624,...,174.191634,140.912805,193.888417,192.458313,210.006736,259.421519,216.662892,161.729110,263.910596,254.120378
강원동해시,32.832761,110.785057,0.000000,9.454969,88.658337,118.287305,75.141194,69.035839,107.420730,102.723800,...,141.840711,92.569542,158.847038,166.314778,191.474382,237.099618,176.520998,120.774804,264.289199,240.721546
강원삼척시,42.145885,120.233443,9.454969,0.000000,98.104205,126.718841,84.535489,68.895896,110.677986,111.351218,...,142.403432,93.137346,158.736792,166.957057,192.415783,237.133637,175.556918,121.025102,266.104274,241.538867
강원속초시,56.412485,22.138478,88.658337,98.104205,0.000000,53.723255,14.807813,114.373119,112.894017,39.898501,...,161.730278,124.583847,181.542495,181.635948,201.022903,250.637464,203.966333,147.404910,259.605572,246.947901

In [3]:
distance_threshold = 126
local_params = 0.6
adj_params = 1 - local_params

In [4]:
dm_with_threshhold = distance_matrix[distance_matrix < distance_threshold]

In [5]:
dm_with_threshhold.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청음성군,충청제천시,충청증평군,충청진천군,충청천안시,충청청양군,충청청주시,충청충주시,충청태안군,충청홍성군
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,0.000000,78.530302,32.832761,42.145885,56.412485,87.339480,42.478539,73.013896,95.861557,71.297142,...,NaN,91.674595,NaN,NaN,NaN,NaN,NaN,119.216734,NaN,NaN
강원고성군,78.530302,0.000000,110.785057,120.233443,22.138478,51.457336,36.408490,NaN,125.138624,43.255624,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원동해시,32.832761,110.785057,0.000000,9.454969,88.658337,118.287305,75.141194,69.035839,107.420730,102.723800,...,NaN,92.569542,NaN,NaN,NaN,NaN,NaN,120.774804,NaN,NaN
강원삼척시,42.145885,120.233443,9.454969,0.000000,98.104205,NaN,84.535489,68.895896,110.677986,111.351218,...,NaN,93.137346,NaN,NaN,NaN,NaN,NaN,121.025102,NaN,NaN
강원속초시,56.412485,22.138478,88.658337,98.104205,0.000000,53.723255,14.807813,114.373119,112.894017,39.898501,...,NaN,124.583847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# dm_with_threshhold의 모든 가중치를 역수로 취하기.
# 가중치가 0일경우 1로 바꾸기.

dm_with_threshhold = dm_with_threshhold.replace(0, 1)
dm_with_threshhold = 1 / dm_with_threshhold

dm_with_threshhold.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청음성군,충청제천시,충청증평군,충청진천군,충청천안시,충청청양군,충청청주시,충청충주시,충청태안군,충청홍성군
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,1.000000,0.012734,0.030457,0.023727,0.017727,0.011450,0.023541,0.013696,0.010432,0.014026,...,NaN,0.010908,NaN,NaN,NaN,NaN,NaN,0.008388,NaN,NaN
강원고성군,0.012734,1.000000,0.009026,0.008317,0.045170,0.019434,0.027466,NaN,0.007991,0.023118,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원동해시,0.030457,0.009026,1.000000,0.105764,0.011279,0.008454,0.013308,0.014485,0.009309,0.009735,...,NaN,0.010803,NaN,NaN,NaN,NaN,NaN,0.008280,NaN,NaN
강원삼척시,0.023727,0.008317,0.105764,1.000000,0.010193,NaN,0.011829,0.014515,0.009035,0.008981,...,NaN,0.010737,NaN,NaN,NaN,NaN,NaN,0.008263,NaN,NaN
강원속초시,0.017727,0.045170,0.011279,0.010193,1.000000,0.018614,0.067532,0.008743,0.008858,0.025064,...,NaN,0.008027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
import numpy as np

# 각 행의 합을 계산
row_sums = dm_with_threshhold.sum(axis=1) - 1

row_sums.head()

docity
강원강릉시    0.338044
강원고성군    0.252020
강원동해시    0.407404
강원삼척시    0.396891
강원속초시    0.324580
dtype: float64

In [8]:
# 각 인접 도시와의 가중치를 총합으로 나눔
normalized_df = dm_with_threshhold.div(row_sums, axis=0) * adj_params

normalized_df.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청음성군,충청제천시,충청증평군,충청진천군,충청천안시,충청청양군,충청청주시,충청충주시,충청태안군,충청홍성군
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,1.183276,0.015068,0.036040,0.028076,0.020975,0.013548,0.027856,0.016206,0.012344,0.016596,...,NaN,0.012907,NaN,NaN,NaN,NaN,NaN,0.009925,NaN,NaN
강원고성군,0.020211,1.587177,0.014327,0.013201,0.071693,0.030845,0.043594,NaN,0.012683,0.036693,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원동해시,0.029904,0.008862,0.981826,0.103842,0.011074,0.008300,0.013066,0.014222,0.009140,0.009558,...,NaN,0.010606,NaN,NaN,NaN,NaN,NaN,0.008129,NaN,NaN
강원삼척시,0.023913,0.008382,0.106593,1.007834,0.010273,NaN,0.011922,0.014628,0.009106,0.009051,...,NaN,0.010821,NaN,NaN,NaN,NaN,NaN,0.008327,NaN,NaN
강원속초시,0.021846,0.055666,0.013900,0.012562,1.232362,0.022939,0.083224,0.010775,0.010916,0.030887,...,NaN,0.009892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# 대각선 행 중 inf가 아닌 행은 0.7으로 만들기

for i in range(len(normalized_df)):
    if normalized_df.iloc[i, i] != np.inf:
        normalized_df.iloc[i, i] = local_params
    else:
        normalized_df.iloc[i, i] = 1

normalized_df.head()

,강원강릉시,강원고성군,강원동해시,강원삼척시,강원속초시,강원양구군,강원양양군,강원영월군,강원원주시,강원인제군,...,충청음성군,충청제천시,충청증평군,충청진천군,충청천안시,충청청양군,충청청주시,충청충주시,충청태안군,충청홍성군
docity,,,,,,,,,,,,,,,,,,,,,
강원강릉시,0.600000,0.015068,0.036040,0.028076,0.020975,0.013548,0.027856,0.016206,0.012344,0.016596,...,NaN,0.012907,NaN,NaN,NaN,NaN,NaN,0.009925,NaN,NaN
강원고성군,0.020211,0.600000,0.014327,0.013201,0.071693,0.030845,0.043594,NaN,0.012683,0.036693,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강원동해시,0.029904,0.008862,0.600000,0.103842,0.011074,0.008300,0.013066,0.014222,0.009140,0.009558,...,NaN,0.010606,NaN,NaN,NaN,NaN,NaN,0.008129,NaN,NaN
강원삼척시,0.023913,0.008382,0.106593,0.600000,0.010273,NaN,0.011922,0.014628,0.009106,0.009051,...,NaN,0.010821,NaN,NaN,NaN,NaN,NaN,0.008327,NaN,NaN
강원속초시,0.021846,0.055666,0.013900,0.012562,0.600000,0.022939,0.083224,0.010775,0.010916,0.030887,...,NaN,0.009892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
result = normalized_df.sum(axis=1)

result[result - 1 > 0.00001]

Series([], dtype: float64)

In [11]:
normalized_df.to_csv('./dataset/distance_normalize_v2.csv')

In [12]:
df = pd.read_csv('./dataset/no_NaN_dataset_final.csv')

df.head()

,행정구역(시도),행정구역(시군구),연도,총인구수(명),유치원 수,초등학교 수,출생건수,사망건수,혼인건수,이혼건수,학령인구(명),총인구수-학령인구(명),행정구역
0,서울특별시,종로구,2010,170578,17,14,1107,852,1011,396,29164,141414,서울특별시 종로구
1,서울특별시,중구,2010,132822,13,12,1170,671,1049,378,19628,113194,서울특별시 중구
2,서울특별시,용산구,2010,244853,19,15,2312,1086,1784,528,37318,207535,서울특별시 용산구
3,서울특별시,성동구,2010,309093,31,20,2886,1226,2306,672,51562,257531,서울특별시 성동구
4,서울특별시,광진구,2010,375463,42,22,3366,1290,2672,811,67422,308041,서울특별시 광진구

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2899 entries, 0 to 2898
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   행정구역(시도)      2899 non-null   object
 1   행정구역(시군구)     2899 non-null   object
 2   연도            2899 non-null   int64
 3   총인구수(명)       2899 non-null   int64
 4   유치원 수         2899 non-null   int64
 5   초등학교 수        2899 non-null   int64
 6   출생건수          2899 non-null   int64
 7   사망건수          2899 non-null   int64
 8   혼인건수          2899 non-null   int64
 9   이혼건수          2899 non-null   int64
 10  학령인구(명)       2899 non-null   int64
 11  총인구수-학령인구(명)  2899 non-null   int64
 12  행정구역          2899 non-null   object
dtypes: int64(10), object(3)
memory usage: 294.6+ KB

In [31]:
def find_cityname_in_df(df, cityname, year):
    sido = cityname[:2]
    sigungu = cityname[2:]
    
    result = df[(df['행정구역(시도)'].str.contains(sido)) & 
                (df['행정구역(시군구)'] == sigungu) & 
                (df['연도'] == year)]
    
    if len(result) != 1:
        result = df[(df['행정구역(시도)'].str.contains(sido)) & 
                (df['행정구역(시군구)'].str.contains(sigungu)) & 
                (df['연도'] == year)]

    if len(result) != 1:
        print("길이는 : " + str(len(result)))
        print(result.head())

    return result

def find_normalizedf_row(do, city):
    matching_rows = normalized_df.index[normalized_df.index.str.contains(do) & normalized_df.index.str.contains(city)]
    if matching_rows.empty:
        return pd.DataFrame()
    else:
        return normalized_df.loc[matching_rows].iloc[0]

In [16]:
from tqdm import tqdm

processed_df = df.copy()
numeric_columns = df.select_dtypes(include=[np.number]).columns
numeric_columns = numeric_columns.drop('학령인구(명)')
error_city_list = []


for i in tqdm(range(len(df))):
    try:
        parts = df.iloc[i]['행정구역(시도)'].split()
        do = parts[0][:2]
        city = df.iloc[i]['행정구역(시군구)']
        year = df.iloc[i]['연도']

        adj_matrix = find_normalizedf_row(do, city)
        row_list = []
        

        weight = 0

        
        #tmp_df = pd.DataFrame(columns=df.columns)
            
        for j in range(len(adj_matrix)):
            try:

                adj_city_name = adj_matrix.index[j]
                adj_city_weight = adj_matrix.iloc[j]
                if pd.isna(adj_city_weight):
                    continue
                
                row = find_cityname_in_df(df, adj_city_name, year)
        
                #tmp_df.insert(row)
                row[numeric_columns] *= adj_city_weight

                
                if(row.empty):
                    error_city_list.append(adj_city_name)
                    continue
                
                row_list.append(row)
            except KeyError:
                print("error 2: " + adj_matrix.index[j])
                continue
        
                
        # Sum all the rows in row_list
        new_row = pd.concat(row_list)
        
        if i == 0:
            print(new_row.head())
        
        new_row = new_row[numeric_columns]
        new_row_sum = new_row.sum()
        
        if i == 0:
            print(new_row_sum.head())

        #if i == 1:
            #print(yearlist)
            #print(new_row['연도'])
        

        # Use .loc to avoid SettingWithCopyWarning
        processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum

    except Exception as e:
        print(f"error 3:  - {str(e)}")
        print(do + " " + city)
        continue

  0%|          | 0/2899 [00:00<?, ?it/s]

/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_97162/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '248849.99868815136' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_97162/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '26.07943836829382' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_97162/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '18.500353429672913' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_97162/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '2029.7460123499757' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_97162/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1102.685739340052' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_97162/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1598.3456429540706' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_97162/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '561.7639619279961' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_97162/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '203918.93657151982' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
  0%|          | 1/2899 [00:00<06:13,  7.76it/s]

    행정구역(시도) 행정구역(시군구)        연도     총인구수(명)     유치원 수    초등학교 수      출생건수  \
115  강원특별자치도       양구군  1.454791   15.809451  0.007238  0.007238  0.148374
102  강원특별자치도       원주시  1.790516  280.316341  0.054339  0.040977  2.618072
116  강원특별자치도       인제군  1.315336   20.837272  0.012434  0.009162  0.252597
113  강원특별자치도       철원군  2.216224   53.947956  0.018744  0.018744  0.511606
101  강원특별자치도       춘천시  2.091852  280.942978  0.040588  0.040588  2.368684

         사망건수      혼인건수      이혼건수  학령인구(명)  총인구수-학령인구(명)         행정구역
115  0.121594  0.112909  0.034017     4070     12.863681  강원특별자치도 양구군
102  1.507240  1.652441  0.686810    68148    219.609847  강원특별자치도 원주시
116  0.165562  0.136114  0.046462     5546     17.207993  강원특별자치도 인제군
113  0.379294  0.288881  0.106952     9201     43.802944  강원특별자치도 철원군
101  1.685970  1.607916  0.599456    55940    222.724974  강원특별자치도 춘천시
연도           2010.000000
총인구수(명)    248849.998688
유치원 수          26.079438
초등학교 수         18.500353
출생건수         2029.746012
dtype: float64

  0%|          | 4/2899 [00:00<05:31,  8.73it/s]/var/folders/39/yhddl2n53db5kx8yl47wsn_m0000gn/T/ipykernel_97162/1015595564.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '2010.0000000000002' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  processed_df.loc[processed_df.index[i], numeric_columns] = new_row_sum
100%|██████████| 2899/2899 [04:23<00:00, 10.99it/s]

In [33]:
processed_df = df.copy()
numeric_columns = df.select_dtypes(include=[np.number]).columns
numeric_columns = numeric_columns.drop('학령인구(명)')
error_city_list = []

for col in numeric_columns:
    processed_df[col] = processed_df[col].astype(float)


# 메인 데이터 처리 루프
for i in tqdm(range(len(df))):
    parts = df.iloc[i]['행정구역(시도)'].split()
    do = parts[0][:2]
    city = df.iloc[i]['행정구역(시군구)']
    year = df.iloc[i]['연도']
    

    try:
        adj_matrix_row = find_normalizedf_row(do, city)
        if adj_matrix_row.empty:
            continue

        tmp_df = pd.DataFrame()
        for adj_city_name in adj_matrix_row.index:
            adj_city_weight = adj_matrix_row[adj_city_name]
            if pd.isna(adj_city_weight):
                continue

# 데이터 조작 전에 .copy() 사용
            row = find_cityname_in_df(df, adj_city_name, year).copy()
            if row.empty:
                error_city_list.append(adj_city_name)
                continue

# 부적합한 데이터 타입 문제 해결
            row[numeric_columns] = row[numeric_columns].astype(float) * adj_city_weight
            tmp_df = pd.concat([tmp_df, row])
            

        new_row_sum = tmp_df[numeric_columns].sum()
        processed_df.loc[i, numeric_columns] = new_row_sum

    except Exception as e:
        print(f"error: {str(e)} - {do} {city}")
        continue

100%|██████████| 2899/2899 [04:38<00:00, 10.43it/s]

In [17]:
print(set(error_city_list))

set()

In [18]:
# procedded_df의 '연도' 컬럼을 반올림해서 int 정수로 바꾸기

processed_df['연도'] = processed_df['연도'].round().astype(int)

In [19]:
processed_df.to_csv('./dataset/weighted_dataset_v6.csv')